SELECT A.CATEGORY, SUM(B.TOTAL_SALES) AS TOTAL_SALES
FROM BOOK A JOIN (SELECT BOOK_ID, SUM(SALES) AS TOTAL_SALES FROM BOOK_SALES WHERE DATE_FORMAT(SALES_DATE,'%Y-%m') = '2022-01' GROUP BY BOOK_ID) B ON A.BOOK_ID=B.BOOK_ID
GROUP BY A.CATEGORY
ORDER BY A.CATEGORY ASC;